---
- name: Install and Create Minikube Cluster
  hosts: target1
  become: true

  tasks:
    - name: Install dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - docker.io
        - conntrack
        - socat
        - curl
    - name: Update the apt package index and install packages needed to use the Kubernetes apt repository
      command: sudo apt-get update  && sudo apt-get install -y ca-certificates curl
    - name: Download the Google Cloud public signing key
      command: sudo curl -fsSLo /etc/apt/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
    - name: Add the Kubernetes apt repository
      command: echo "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
    - name: Update apt package index with the new repository and install kubectl
      command: sudo apt-get update && sudo apt-get install -y kubectl

    - name: Install Minikube
      shell: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube

    - name: Start Minikube cluster
      shell: |
        minikube start --driver=docker

    - name: Set kubectl context
      shell: |
        minikube update-context

    - name: Verify cluster status
      shell: |
        kubectl cluster-info
